export const PAGE_STATE = {
    "Home": 0,
    "Careers": 1,
    "Majors": 2
}

export const UNI_COLORS = {
    'University of California-Berkeley': '#ffcc00',
    'University of California-Davis': '#ff6666',
    'University of California-Irvine': '#cc0066',
    'University of California-Los Angeles': '#66cccc',
    'University of California-Merced': '#f688bb',
    'University of California-Riverside': '#baf1a1',
    'University of California-San Diego': '#0c7b93',
    'University of California-Santa Barbara': '#75b79e',
    'University of California-Santa Cruz': '#9de3d0'
}

export const MAJOR_CATEGORIES = [    
    "Agriculture & Environmental Studies",
    "Arts & Design",
    "Human & Public Services",
    "Natural Sciences",
    "Engineering & Technology",
    "Humanities",
    "Social & Political Sciences",
    "Business & Management", 
    "Health & Psychology",
    "Mathematics & Economics"
]

export const MAJOR_IMG = [
    "./assets/planets/ag.png",
    "./assets/planets/art.png",
    "./assets/planets/services.png",
    "./assets/planets/science.png",
    "./assets/planets/engineering.png",
    "./assets/planets/humanities.png",
    "./assets/planets/social.png",
    "./assets/planets/business.png",
    "./assets/planets/health.png",
    "./assets/planets/math.png"
]

export const MINOR_CATEGORIES = {
    "Agriculture & Environmental Studies": 
        ["Agriculture & Food Science",
         "Environmental Science & Studies",
         "Animal Science"],
    "Arts & Design": 
        ["General Art",
         "Design",
         "Music",
         "Cinema & Visual Arts",
         "Performing Arts"],
    "Human & Public Services": 
        ["Education",
         "Law & Criminology",
         "Social Services"],
    "Natural Sciences": 
        ["Earth Sciences",
         "Physics & Astronomy",
         "Biology",
         "Chemistry"],
    "Engineering & Technology": 
        ["Information & Technology",
         "Specializations & Engineering",
         "Electrical & Mechanical Engineering",
         "Computer Science and Engineering",
         "City Planning & Architecture"],
    "Humanities": 
        ["Cultural & Ethnic Studies",
         "Feminist & Gender Studies",
         "Philosophy & Religion",
         "Language & Literature",
         "Anthropology & History",
         "General Humanities",
         "Communication & Journalism"],
    "Social & Political Sciences": 
        ["Politics & Public Policy",
         "Sociology",
         "Linguistics"],
    "Business & Management": 
        ["Management & Information Systems",
         "Accounting & Finance",
         "Marketing & Consumer Services",
         "Specializations & Business"],
    "Health & Psychology": 
        ["Food & Nutrition",
         "Psychology",
         "Medical Sciences",
         "Athletic & Bodily Science"],
    "Mathematics & Economics": 
        ["Statistics & Data Science",
         "Applied & General Mathematics",
         "Economics"]
}

export const MAJOR_COLORS = {
    "Agriculture & Environmental Studies": '#def05aff',
    "Arts & Design": '#fc8bc0ff',
    "Human & Public Services": '#fda8a7ff',
    "Natural Sciences": '#c77ee6ff',
    "Engineering & Technology": '#82c0d8ff',
    "Humanities": '#fee28cff',
    "Social & Political Sciences": '#eb8a6fff',
    "Business & Management": '#ffb45eff',
    "Health & Psychology": '#ecb3f1ff',
    "Mathematics & Economics": '#9de4e2ff'
}

export const MAJOR_POSITIONS = {
    "Agriculture & Environmental Studies": [0.22576468, 0.78682877],
    "Arts & Design": [0.62719317, 0.46743662],
    "Human & Public Services": [0.12048579, 0.44192509],
    "Natural Sciences": [0.76058128, 0.81376119],
    "Engineering & Technology": [0.76394922, 0.19356788],
    "Humanities": [0.509, 0.21],
    "Social & Political Sciences": [0.23993193, 0.1631277],
    "Business & Management": [0.86995319, 0.5784954],
    "Health & Psychology": [0.3584272 , 0.49914542],
    "Mathematics & Economics": [0.49405762, 0.79226853]
}


export const MINOR_COLORS = {
    "Agriculture & Food Science":  '#849502',
    "Environmental Science & Studies": '#B8D102',
    "Animal Science": '#E1FD12',
    "General Art": '#B30053',
    "Design": '#FA0075',
    "Music": '#FF429A',
    "Cinema & Visual Arts": '#FF75B6',
    "Performing Arts": '#FF94C6', 
    "Education": '#FE4B48',
    "Law & Criminology": '#fd8987',
    "Social Services": '#FDA8A7',
    "Earth Sciences": '#8804C0',
    "Physics & Astronomy": '#B20BFA',
    "Biology": '#C64BFB',
    "Chemistry": '#D26FFC', 
    "Information & Technology": '#0685B8',
    "Specializations & Engineering": '#08B2F5',
    "Electrical & Mechanical Engineering": '#43C6F9',
    "Computer Science and Engineering": '#69D1FA',
    "City Planning & Architecture": '#8EDDFC',
    "Cultural & Ethnic Studies": '#B38600',
    "Feminist & Gender Studies": '#D6A100',
    "Philosophy & Religion": '#FABB00',
    "Language & Literature": '#FFC71F',
    "Anthropology & History": '#FFD042',
    "General Humanities": '#FFD966',
    "Communication & Journalism": '#FFDD75',
    "Politics & Public Policy": '#DB4016',
    "Sociology": '#FD5020',
    "Linguistics": '#FD7752',
    "Management & Information Systems": '#BE6500',
    "Accounting & Finance": '#FD8700',
    "Marketing & Consumer Services": '#FF961E',
    "Specializations & Business": '#FFA53D', 
    "Food & Nutrition": '#CE06E0',
    "Psychology": '#EA38FA',
    "Medical Sciences": '#F283FC',
    "Athletic & Bodily Science": '#F49CFC',
    "Statistics & Data Science": '#04A9A4',
    "Applied & General Mathematics": '#06EDE5',
    "Economics": '#3EFAF4'
}

export const MINOR_IMG = {
    "Agriculture & Food Science":  'https://www.bestdegreeprograms.org/wp-content/uploads/2021/12/shutterstock_1996125254-scaled.jpg',
    "Environmental Science & Studies": 'https://cnr.ncsu.edu/news/wp-content/uploads/sites/10/2019/10/Woman_Using_Environmental_Science_Degree.jpg',
    "Animal Science": 'https://www.gannett-cdn.com/-mm-/bafa1853d7742f5294f01daeb4a092f6e163abb2/c=0-14-2063-1180/local/-/media/2017/02/27/USATODAY/USATODAY/636237888837399939-GettyImages-480255976.jpg?width=1200&disable=upscale&format=pjpg&auto=webp',
    "General Art": 'https://i.insider.com/5a9dac90e6a9cf32018b463a?width=700',
    "Design": 'https://dpbnri2zg3lc2.cloudfront.net/en/wp-content/uploads/2021/12/ux-indemanddesignjobs-header-min.jpg',
    "Music": 'https://www.sweetwater.com/insync/media/2020/06/Suprising-Jobs-in-the-Music-Featured-Image.jpg',
    "Cinema & Visual Arts": 'https://www.toronto.ca/wp-content/uploads/2021/04/977b-landingpage-social.jpg',
    "Performing Arts": 'https://www.planitplus.net/CareerAreaImages/20.jpg',
    "Education": 'https://jobs.theguardian.com/getasset/32fe78c2-ff08-4788-a60c-2693c9605dbf/',
    "Law & Criminology": 'https://storage-prtl-co.imgix.net/mp/919e6e5f.jpg?w=800&h=532&auto=format,compress&q=40',
    "Social Services": 'https://www.onlinemswprograms.com/wp-content/uploads/sites/55/2021/05/social-work-careers_hero_1.jpeg',
    "Earth Sciences": 'https://s2.research.com/wp-content/uploads/2020/07/24110114/geologist-1-1-1200x600.jpg',
    "Physics & Astronomy": 'https://naturalsciences.org/images/research/astronomy-astrophysics/astroLab04.jpg',
    "Biology": 'https://cf.ltkcdn.net/jobs/images/orig/288066-1600x1066-biology-careers.jpg',
    "Chemistry": 'https://www.thoughtco.com/thmb/zcryu9QwZzawZmfEexLzjcptIZI=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/GettyImages-623208226-58a0a8623df78c4758d3220d.jpg', 
    "Information & Technology": 'https://www.cambridgehealth.edu/wp-content/uploads/2020/05/hitblog.jpg',
    "Specializations & Engineering": 'https://www.vaughn.edu/wp-content/uploads/2021/01/Mechanical-Engineering-Jobs_Feature.jpg',
    "Electrical & Mechanical Engineering": 'https://www.excelsior.edu/wp-content/uploads/2022/06/GettyImages-1319077259_Blog_1000x568-1000x568.jpeg',
    "Computer Science and Engineering": 'https://res.cloudinary.com/highereducation/images/f_auto,q_auto/c_fill,f_auto,fl_lossy,q_auto:best/v1631898410/ComputerScience.org/GettyImages-1194430821/GettyImages-1194430821.jpg?_i=AA',
    "City Planning & Architecture": 'https://images.interestingengineering.com/1200x675/images/engineering-career.jpg',
    "Cultural & Ethnic Studies": 'https://www.mcnayart.org/wp-content/uploads/2020/10/20180404_patron-gallery-talk-web-115_copy.jpg',
    "Feminist & Gender Studies": 'https://www.careergirls.org/wp-content/uploads/2018/05/Writer_1920x1080.jpg',
    "Philosophy & Religion": 'https://www.ziprecruiter.com/svc/fotomat/public-ziprecruiter/cms/962475880PhilosophyProfessor.jpg',
    "Language & Literature": 'https://photos.demandstudios.com/getty/article/94/145/109592736.jpg',
    "Anthropology & History": 'https://www.geteducated.com/wp-content/uploads/2021/09/anthropology-photo-1140x400.jpg',
    "General Humanities": 'https://s2.research.com/wp-content/uploads/2021/08/31105109/art-history-career-1200x600.jpg',
    "Communication & Journalism": 'https://online.sbu.edu/sites/default/files/field/image/journalism_good_career1.jpg',
    "Politics & Public Policy": 'https://s2.research.com/wp-content/uploads/2021/10/07181213/public-policy-careers-1200x600.jpg',
    "Sociology": 'https://s2.research.com/wp-content/uploads/2021/10/07181213/public-policy-careers-1200x600.jpg',
    "Linguistics": 'https://www.canterbury.ac.nz/careers/subjects/linguistics/t4_2988340531143690150.jpg',
    "Management & Information Systems": 'https://s2.research.com/wp-content/uploads/2021/06/24110237/business-management-career-1-1200x600.jpg',
    "Accounting & Finance": 'https://bachelors-completion.northeastern.edu/wp-content/uploads/2018/07/finance-and-accounting-careers-2-1.jpg',
    "Marketing & Consumer Services": 'https://149902252.v2.pressablecdn.com/wp-content/uploads/2022/04/marketing-careers-1200x630-1.jpg',
    "Specializations & Business": 'https://d3tl80hy6t5toy.cloudfront.net/wp-content/uploads/sites/3/2014/06/07141300/best-business-careers1.jpg',
    "Food & Nutrition": 'https://149922190.v2.pressablecdn.com/wp-content/uploads/2020/02/dietitian-careers-750-x-350.jpg',
    "Psychology": 'https://www.waldenu.edu/media/5487/seo-2344-bs-effective-therapy-happy-young-432700976-1200x675',
    "Medical Sciences": 'https://www.usnews.com/object/image/00000152-478d-d86f-a7f6-cfdf245b0000/160115-medicalstudents-stock.jpg?update-time=1452899488353&size=responsive640',
    "Athletic & Bodily Science": 'https://www.sfasu.edu/sites/default/files/2021-05/athletic-training-primary-image.jpg',
    "Statistics & Data Science": 'https://onlinedegrees.sandiego.edu/wp-content/uploads/2020/09/usd-data-science-jobs-1.jpeg',
    "Applied & General Mathematics": 'https://fbijobs.gov/sites/default/files/styles/webp/public/2022-07/adobestock_351530009_edited_1.jpg.webp?itok=HXEfRGFi',
    "Economics": 'https://www.northeastern.edu/graduate/blog/wp-content/uploads/2020/10/iStock-1223455289-1.jpg'
}

export const MINOR_IMG2 = {
    "Agriculture & Food Science":  './assets/jobs-img/social.jpg',
    "Environmental Science & Studies": './assets/jobs-img/social.jpg',
    "Animal Science": './assets/jobs-img/social.jpg',
    "General Art": './assets/jobs-img/social.jpg',
    "Design": './assets/jobs-img/social.jpg',
    "Music": './assets/jobs-img/social.jpg',
    "Cinema & Visual Arts": './assets/jobs-img/social.jpg',
    "Performing Arts": './assets/jobs-img/social.jpg',
    "Education": './assets/jobs-img/social.jpg',
    "Law & Criminology": './assets/jobs-img/social.jpg',
    "Social Services": './assets/jobs-img/social.jpg',
    "Earth Sciences": './assets/jobs-img/social.jpg',
    "Physics & Astronomy": './assets/jobs-img/social.jpg',
    "Biology": './assets/jobs-img/social.jpg',
    "Chemistry": './assets/jobs-img/social.jpg', 
    "Information & Technology": './assets/jobs-img/social.jpg',
    "Specializations & Engineering": './assets/jobs-img/social.jpg',
    "Electrical & Mechanical Engineering": './assets/jobs-img/social.jpg',
    "Computer Science and Engineering": './assets/jobs-img/social.jpg',
    "City Planning & Architecture": './assets/jobs-img/social.jpg',
    "Cultural & Ethnic Studies": './assets/jobs-img/social.jpg',
    "Feminist & Gender Studies": './assets/jobs-img/social.jpg',
    "Philosophy & Religion": './assets/jobs-img/social.jpg',
    "Language & Literature": './assets/jobs-img/social.jpg',
    "Anthropology & History": './assets/jobs-img/social.jpg',
    "General Humanities": './assets/jobs-img/social.jpg',
    "Communication & Journalism": './assets/jobs-img/social.jpg',
    "Politics & Public Policy": './assets/jobs-img/social.jpg',
    "Sociology": './assets/jobs-img/social.jpg',
    "Linguistics": './assets/jobs-img/social.jpg',
    "Management & Information Systems": './assets/jobs-img/social.jpg',
    "Accounting & Finance": './assets/jobs-img/social.jpg',
    "Marketing & Consumer Services": './assets/jobs-img/social.jpg',
    "Specializations & Business": './assets/jobs-img/social.jpg',
    "Food & Nutrition": './assets/jobs-img/social.jpg',
    "Psychology": './assets/jobs-img/social.jpg',
    "Medical Sciences": './assets/jobs-img/social.jpg',
    "Athletic & Bodily Science": './assets/jobs-img/social.jpg',
    "Statistics & Data Science": './assets/jobs-img/social.jpg',
    "Applied & General Mathematics": './assets/jobs-img/social.jpg',
    "Economics": './assets/jobs-img/social.jpg'
}