export const PAGE_STATE = {
    "Home": 0,
    "Careers": 1,
    "Majors": 2
}

export const UNI_COLORS = {
    'University of California-Berkeley': '#ffcc00',
    'University of California-Davis': '#ff6666',
    'University of California-Irvine': '#cc0066',
    'University of California-Los Angeles': '#66cccc',
    'University of California-Merced': '#f688bb',
    'University of California-Riverside': '#baf1a1',
    'University of California-San Diego': '#0c7b93',
    'University of California-Santa Barbara': '#75b79e',
    'University of California-Santa Cruz': '#9de3d0'
}

export const MAJOR_CATEGORIES = [    
    "Agriculture & Environmental Studies",
    "Arts & Design",
    "Human & Public Services",
    "Natural Sciences",
    "Engineering & Technology",
    "Humanities",
    "Social & Political Sciences",
    "Business & Management", 
    "Health & Psychology",
    "Mathematics & Economics"
]

export const MAJOR_IMG = [
    "./assets/planets/ag.png",
    "./assets/planets/art.png",
    "./assets/planets/services.png",
    "./assets/planets/science.png",
    "./assets/planets/engineering.png",
    "./assets/planets/humanities.png",
    "./assets/planets/social.png",
    "./assets/planets/business.png",
    "./assets/planets/health.png",
    "./assets/planets/math.png"
]

export const MINOR_CATEGORIES = {
    "Agriculture & Environmental Studies": 
        ["Agriculture & Food Science",
         "Environmental Science & Studies",
         "Animal Science"],
    "Arts & Design": 
        ["General Art",
         "Design",
         "Music",
         "Cinema & Visual Arts",
         "Performing Arts"],
    "Human & Public Services": 
        ["Education",
         "Law & Criminology",
         "Social Services"],
    "Natural Sciences": 
        ["Earth Sciences",
         "Physics & Astronomy",
         "Biology",
         "Chemistry"],
    "Engineering & Technology": 
        ["Information & Technology",
         "Specializations & Engineering",
         "Electrical & Mechanical Engineering",
         "Computer Science and Engineering",
         "City Planning & Architecture"],
    "Humanities": 
        ["Cultural & Ethnic Studies",
         "Feminist & Gender Studies",
         "Philosophy & Religion",
         "Language & Literature",
         "Anthropology & History",
         "General Humanities",
         "Communication & Journalism"],
    "Social & Political Sciences": 
        ["Politics & Public Policy",
         "Sociology",
         "Linguistics"],
    "Business & Management": 
        ["Management & Information Systems",
         "Accounting & Finance",
         "Marketing & Consumer Services",
         "Specializations & Business"],
    "Health & Psychology": 
        ["Food & Nutrition",
         "Psychology",
         "Medical Sciences",
         "Athletic & Bodily Science"],
    "Mathematics & Economics": 
        ["Statistics & Data Science",
         "Applied & General Mathematics",
         "Economics"]
}

export const MAJOR_COLORS = {
    "Agriculture & Environmental Studies": '#def05aff',
    "Arts & Design": '#fc8bc0ff',
    "Human & Public Services": '#fda8a7ff',
    "Natural Sciences": '#c77ee6ff',
    "Engineering & Technology": '#82c0d8ff',
    "Humanities": '#fee28cff',
    "Social & Political Sciences": '#eb8a6fff',
    "Business & Management": '#ffb45eff',
    "Health & Psychology": '#ecb3f1ff',
    "Mathematics & Economics": '#9de4e2ff'
}

export const MAJOR_POSITIONS = {
    "Agriculture & Environmental Studies": [0.22576468, 0.78682877],
    "Arts & Design": [0.62719317, 0.46743662],
    "Human & Public Services": [0.12048579, 0.44192509],
    "Natural Sciences": [0.76058128, 0.81376119],
    "Engineering & Technology": [0.76394922, 0.19356788],
    "Humanities": [0.509, 0.21],
    "Social & Political Sciences": [0.23993193, 0.1631277],
    "Business & Management": [0.86995319, 0.5784954],
    "Health & Psychology": [0.3584272 , 0.49914542],
    "Mathematics & Economics": [0.49405762, 0.79226853]
}


export const MINOR_COLORS = {
    "Agriculture & Food Science":  '#849502',
    "Environmental Science & Studies": '#B8D102',
    "Animal Science": '#E1FD12',
    "General Art": '#B30053',
    "Design": '#FA0075',
    "Music": '#FF429A',
    "Cinema & Visual Arts": '#FF75B6',
    "Performing Arts": '#FF94C6', 
    "Education": '#FE4B48',
    "Law & Criminology": '#fd8987',
    "Social Services": '#FDA8A7',
    "Earth Sciences": '#8804C0',
    "Physics & Astronomy": '#B20BFA',
    "Biology": '#C64BFB',
    "Chemistry": '#D26FFC', 
    "Information & Technology": '#0685B8',
    "Specializations & Engineering": '#08B2F5',
    "Electrical & Mechanical Engineering": '#43C6F9',
    "Computer Science and Engineering": '#69D1FA',
    "City Planning & Architecture": '#8EDDFC',
    "Cultural & Ethnic Studies": '#B38600',
    "Feminist & Gender Studies": '#D6A100',
    "Philosophy & Religion": '#FABB00',
    "Language & Literature": '#FFC71F',
    "Anthropology & History": '#FFD042',
    "General Humanities": '#FFD966',
    "Communication & Journalism": '#FFDD75',
    "Politics & Public Policy": '#DB4016',
    "Sociology": '#FD5020',
    "Linguistics": '#FD7752',
    "Management & Information Systems": '#BE6500',
    "Accounting & Finance": '#FD8700',
    "Marketing & Consumer Services": '#FF961E',
    "Specializations & Business": '#FFA53D', 
    "Food & Nutrition": '#CE06E0',
    "Psychology": '#EA38FA',
    "Medical Sciences": '#F283FC',
    "Athletic & Bodily Science": '#F49CFC',
    "Statistics & Data Science": '#04A9A4',
    "Applied & General Mathematics": '#06EDE5',
    "Economics": '#3EFAF4'
}

export const MINOR_IMG = {
    "Agriculture & Food Science":  'https://www.bestdegreeprograms.org/wp-content/uploads/2021/12/shutterstock_1996125254-scaled.jpg',
    "Environmental Science & Studies": 'https://cnr.ncsu.edu/news/wp-content/uploads/sites/10/2019/10/Woman_Using_Environmental_Science_Degree.jpg',
    "Animal Science": 'https://www.gannett-cdn.com/-mm-/bafa1853d7742f5294f01daeb4a092f6e163abb2/c=0-14-2063-1180/local/-/media/2017/02/27/USATODAY/USATODAY/636237888837399939-GettyImages-480255976.jpg?width=1200&disable=upscale&format=pjpg&auto=webp',
    "General Art": 'https://i.insider.com/5a9dac90e6a9cf32018b463a?width=700',
    "Design": 'https://dpbnri2zg3lc2.cloudfront.net/en/wp-content/uploads/2021/12/ux-indemanddesignjobs-header-min.jpg',
    "Music": 'https://www.sweetwater.com/insync/media/2020/06/Suprising-Jobs-in-the-Music-Featured-Image.jpg',
    "Cinema & Visual Arts": 'https://www.toronto.ca/wp-content/uploads/2021/04/977b-landingpage-social.jpg',
    "Performing Arts": 'https://www.planitplus.net/CareerAreaImages/20.jpg',
    "Education": './assets/jobs-img/social.jpg',
    "Law & Criminology": '/assets/jobs-img/social.jpg',
    "Social Services": '/assets/jobs-img/social.jpg',
    "Earth Sciences": '/assets/jobs-img/social.jpg',
    "Physics & Astronomy": '/assets/jobs-img/social.jpg',
    "Biology": '/assets/jobs-img/social.jpg',
    "Chemistry": '/assets/jobs-img/social.jpg', 
    "Information & Technology": '/assets/jobs-img/social.jpg',
    "Specializations & Engineering": '/assets/jobs-img/social.jpg',
    "Electrical & Mechanical Engineering": '/assets/jobs-img/social.jpg',
    "Computer Science and Engineering": '/assets/jobs-img/social.jpg',
    "City Planning & Architecture": '/assets/jobs-img/social.jpg',
    "Cultural & Ethnic Studies": '/assets/jobs-img/social.jpg',
    "Feminist & Gender Studies": '/assets/jobs-img/social.jpg',
    "Philosophy & Religion": '/assets/jobs-img/social.jpg',
    "Language & Literature": '/assets/jobs-img/social.jpg',
    "Anthropology & History": '/assets/jobs-img/social.jpg',
    "General Humanities": '/assets/jobs-img/social.jpg',
    "Communication & Journalism": '/assets/jobs-img/social.jpg',
    "Politics & Public Policy": '/assets/jobs-img/social.jpg',
    "Sociology": '/assets/jobs-img/social.jpg',
    "Linguistics": '/assets/jobs-img/social.jpg',
    "Management & Information Systems": '/assets/jobs-img/social.jpg',
    "Accounting & Finance": '/assets/jobs-img/social.jpg',
    "Marketing & Consumer Services": '/assets/jobs-img/social.jpg',
    "Specializations & Business": '/assets/jobs-img/social.jpg',
    "Food & Nutrition": '/assets/jobs-img/social.jpg',
    "Psychology": '/assets/jobs-img/social.jpg',
    "Medical Sciences": '/assets/jobs-img/social.jpg',
    "Athletic & Bodily Science": '/assets/jobs-img/social.jpg',
    "Statistics & Data Science": '/assets/jobs-img/social.jpg',
    "Applied & General Mathematics": '/assets/jobs-img/social.jpg',
    "Economics": '/assets/jobs-img/social.jpg'
}

export const MINOR_IMG2 = {
    "Agriculture & Food Science":  './assets/jobs-img/social.jpg',
    "Environmental Science & Studies": './assets/jobs-img/social.jpg',
    "Animal Science": './assets/jobs-img/social.jpg',
    "General Art": './assets/jobs-img/social.jpg',
    "Design": './assets/jobs-img/social.jpg',
    "Music": './assets/jobs-img/social.jpg',
    "Cinema & Visual Arts": './assets/jobs-img/social.jpg',
    "Performing Arts": './assets/jobs-img/social.jpg',
    "Education": './assets/jobs-img/social.jpg',
    "Law & Criminology": './assets/jobs-img/social.jpg',
    "Social Services": './assets/jobs-img/social.jpg',
    "Earth Sciences": './assets/jobs-img/social.jpg',
    "Physics & Astronomy": './assets/jobs-img/social.jpg',
    "Biology": './assets/jobs-img/social.jpg',
    "Chemistry": './assets/jobs-img/social.jpg', 
    "Information & Technology": './assets/jobs-img/social.jpg',
    "Specializations & Engineering": './assets/jobs-img/social.jpg',
    "Electrical & Mechanical Engineering": './assets/jobs-img/social.jpg',
    "Computer Science and Engineering": './assets/jobs-img/social.jpg',
    "City Planning & Architecture": './assets/jobs-img/social.jpg',
    "Cultural & Ethnic Studies": './assets/jobs-img/social.jpg',
    "Feminist & Gender Studies": './assets/jobs-img/social.jpg',
    "Philosophy & Religion": './assets/jobs-img/social.jpg',
    "Language & Literature": './assets/jobs-img/social.jpg',
    "Anthropology & History": './assets/jobs-img/social.jpg',
    "General Humanities": './assets/jobs-img/social.jpg',
    "Communication & Journalism": './assets/jobs-img/social.jpg',
    "Politics & Public Policy": './assets/jobs-img/social.jpg',
    "Sociology": './assets/jobs-img/social.jpg',
    "Linguistics": './assets/jobs-img/social.jpg',
    "Management & Information Systems": './assets/jobs-img/social.jpg',
    "Accounting & Finance": './assets/jobs-img/social.jpg',
    "Marketing & Consumer Services": './assets/jobs-img/social.jpg',
    "Specializations & Business": './assets/jobs-img/social.jpg',
    "Food & Nutrition": './assets/jobs-img/social.jpg',
    "Psychology": './assets/jobs-img/social.jpg',
    "Medical Sciences": './assets/jobs-img/social.jpg',
    "Athletic & Bodily Science": './assets/jobs-img/social.jpg',
    "Statistics & Data Science": './assets/jobs-img/social.jpg',
    "Applied & General Mathematics": './assets/jobs-img/social.jpg',
    "Economics": './assets/jobs-img/social.jpg'
}